export { default as ForgotPassword } from './ForgotPassword'
export { default as KeepInTouch } from './KeepInTouch'
export { default as LoginView } from './LoginView'
export { default as RecoverView } from './RecoverView'
export { default as Register } from './Register'
export { default as ResetView } from './ResetView'
